-- Your SQL goes here
CREATE TABLE users (
  id VARCHAR PRIMARY KEY ON DELETE CASCADE,
  username VARCHAR NOT NULL UNIQUE,
  email VARCHAR NOT NULL UNIQUE,
  salt VARCHAR NOT NULL,
  password VARCHAR NOT NULL
)